export { orchestrateTTS, estimateTTSCost } from './tts/index.js'
export { preflightCheck } from './preflight.js'
export { renderVideo } from './render/index.js'
export { generateSRT } from './render/srt.js'
export type { PreflightResult } from './preflight.js'
export type { RenderProgress, RenderOptions } from './render/index.js'
export type { TTSOptions, SceneAudio, AudioManifest, TTSCostEstimate } from './tts/types.js'
export type { BuildStoryInputProps, BeatWithFrames } from './render/composition/types.js'
